### ISSUE TITLE
(Psi1.2-83 and psitools 3.0.4) Issue rendering mod item ItemBlockPsiCore in JEI 6.0.2.12

### ISSUE THREAD

**Issue by Enderborn1235** [Macrophage001/PsiTools#2]
Expected Behavior: Items(BlockPsiCore in particular) added in the mod wouldn't crash the game.

Current Behavior: Scolling to the items(BlockPsiCore in particular) added from the mod in JEI crashes the game.

Steps to Reproduce: Scrolling to the item labeled "ItemBlockPsiCore" the mod has in JEI.

[crash-2020-08-16_19.08.05-client.txt](https://github.com/Macrophage001/PsiTools/files/5081595/crash-2020-08-16_19.08.05-client.txt)

**Comment by Macrophage001** [comment]
Huh, how weird. I'm going to take a look and see if I can get that fixed.

**Comment by Macrophage001** [comment]
I believe I've fixed it. Basically it was me being a dingus not checking something properly.
