### ISSUE TITLE
(Psi1.2-83 and psitools 0.3.5) Casting "Capture" (Entity) using "Selector:Focal Point" and projectile spell bullet on a block crashes the game

### ISSUE THREAD

**Issue by Enderborn1235** [Macrophage001/PsiTools#3]
Expected Behavior: Capturing an entity on a block using a projectile spell bullet wouldn't crash the game

Current Behavior: Capturing an entity using a projectile speel bullet crashes the game when projectile hits block

Steps to Reproduce: Cast "Capture" with target being "Focal Point" with a projectile spell bullet

Note: Might be an issue with Psi

Note 2: Some pieces added by this addon are missing textures, mainly certain operators and (possibly) the selector piece
[crash-2020-08-19_07.46.39-server.txt](https://github.com/Macrophage001/PsiTools/files/5100150/crash-2020-08-19_07.46.39-server.txt)

**Comment by Macrophage001** [comment]
Seems like the primary issue was that you were trying to capture the spell projectile itself which confused the hell out of the spell. Added a few extra checks to make sure that doesn't happen.
